[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "lance-bundle"
dynamic = ["version"]
description = "Portable, self-contained embedding and vector database bundles."
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "cloudkj", email = "cloudkj@users.noreply.github.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
]
dependencies = [
    "lancedb",
    "pyarrow",
    "onnxruntime",
    "tokenizers",
    "numpy"
]

[project.optional-dependencies]
export = [
    "torch",
    "transformers",
    "onnxscript",
    "optimum[onnxruntime]",
    "sentence-transformers"
]
hub = [
    "huggingface_hub"
]
test = [
    "pytest>=7.0",
    "sentence-transformers",
    "torch"
]

[project.urls]
Homepage = "https://github.com/cloudkj/lance-bundle"

[project.scripts]
lance-bundle = "lance_bundle.cli:main"

[tool.hatch.version]
source = "vcs"
